integration-tests/samples/2.x/IntegrationTestsSample/src/RazorPagesProject/Pages/About.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace RazorPagesProject.Pages
{
    public class AboutModel : PageModel
    {
        public string Message { get; set; }

        public void OnGet()
        {
            Message = "Your application description page.";
        }
    }
}

integration-tests/samples/2.x/IntegrationTestsSample/src/RazorPagesProject/Pages/Contact.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace RazorPagesProject.Pages
{
    public class ContactModel : PageModel
    {
        public string Message { get; set; }

        public void OnGet()
        {
            Message = "Your contact page.";
        }
    }
}

integration-tests/samples/2.x/IntegrationTestsSample/src/RazorPagesProject/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace RazorPagesProject.Pages
{
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

integration-tests/samples/2.x/IntegrationTestsSample/src/RazorPagesProject/Pages/GithubProfile.cshtml.cs
using System.ComponentModel.DataAnnotations;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RazorPagesProject.Services;

namespace RazorPagesProject.Pages
{
    public class GithubProfileModel : PageModel
    {
        public GithubProfileModel(IGithubClient client)
        {
            Client = client;
        }

        public class InputModel
        {
            [Required]
            public string UserName { get; set; }
        }

        [BindProperty]
        public InputModel Input { get; set; }

        public IGithubClient Client { get; }

        public GithubUser GithubUser { get; private set; }

        public async Task<IActionResult> OnGetAsync([FromRoute] string userName)
        {
            if (userName != null)
            {
                GithubUser = await Client.GetUserAsync(userName);
            }

            return Page();
        }

        public IActionResult OnPost()
        {
            if (string.IsNullOrEmpty(Input.UserName))
            {
                return Page();
            }

            return RedirectToPage(new { Input.UserName });
        }
    }
}

integration-tests/samples/2.x/IntegrationTestsSample/src/RazorPagesProject/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RazorPagesProject.Data;

namespace RazorPagesProject.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ApplicationDbContext _db;

        public IndexModel(ApplicationDbContext db)
        {
            _db = db;
        }

        [BindProperty]
        public Message Message { get; set; }

        public IList<Message> Messages { get; private set; }

        [TempData]
        public string MessageAnalysisResult { get; set; }

        #region snippet1
        public async Task OnGetAsync()
        {
            Messages = await _db.GetMessagesAsync();
        }
        #endregion

        public async Task<IActionResult> OnPostAddMessageAsync()
        {
            if (!ModelState.IsValid)
            {
                Messages = await _db.GetMessagesAsync();

                return Page();
            }

            await _db.AddMessageAsync(Message);

            return RedirectToPage();
        }

        public async Task<IActionResult> OnPostDeleteAllMessagesAsync()
        {
            await _db.DeleteAllMessagesAsync();

            return RedirectToPage();
        }

        public async Task<IActionResult> OnPostDeleteMessageAsync(int id)
        {
            await _db.DeleteMessageAsync(id);

            return RedirectToPage();
        }

        public async Task<IActionResult> OnPostAnalyzeMessagesAsync()
        {
            Messages = await _db.GetMessagesAsync();

            if (Messages.Count == 0)
            {
                MessageAnalysisResult = "There are no messages to analyze.";
            }
            else
            {
                var wordCount = 0;

                foreach (var message in Messages)
                {
                    wordCount += message.Text.Split(' ').Length;
                }

                var avgWordCount = Decimal.Divide(wordCount, Messages.Count);
                MessageAnalysisResult = $"The average message length is {avgWordCount:0.##} words.";
            }

            return RedirectToPage();
        }
    }
}

integration-tests/samples/2.x/IntegrationTestsSample/src/RazorPagesProject/Pages/Privacy.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace RazorPagesProject.Pages
{
    public class PrivacyModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

integration-tests/samples/2.x/IntegrationTestsSample/src/RazorPagesProject/Pages/SecurePage.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace RazorPagesProject.Pages
{
    public class SecurePageModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

integration-tests/samples/2.x/IntegrationTestsSample/src/RazorPagesProject/Pages/About.cshtml
@page
@model AboutModel
@{
    ViewData["Title"] = "About";
}

<h1>@ViewData["Title"]</h1>
<h2>@Model.Message</h2>

<p>Use this area to provide additional information.</p>

integration-tests/samples/2.x/IntegrationTestsSample/src/RazorPagesProject/Pages/Contact.cshtml
@page
@model ContactModel
@{
    ViewData["Title"] = "Contact";
}

<h1>@ViewData["Title"]</h1>
<h2>@Model.Message</h2>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

integration-tests/samples/2.x/IntegrationTestsSample/src/RazorPagesProject/Pages/GithubProfile.cshtml
@page "{userName?}"
@model GithubProfileModel
@{
    ViewData["Title"] = "Github Profile";
}

<h1>GithubProfile</h1>

<div class="row">
    <div class="col-md-4">
        <section>
            <form id="user-profile" method="post">
                <h2>Introduce a Github user name.</h2>
                <hr />
                <div asp-validation-summary="All" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="Input.UserName"></label>
                    <input asp-for="Input.UserName" class="form-control" />
                    <span asp-validation-for="Input.UserName" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <button type="submit" class="btn btn-default">Show user profile!</button>
                </div>
            </form>
        </section>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        @if (Model.GithubUser != null)
        {
            <p class="h3">Login</p>
            <p id="user-login">@Model.GithubUser.Login</p>
            <p class="h3">Name</p>
            <p>@Model.GithubUser.Name</p>
            <p class="h3">Company</p>
            <p>@Model.GithubUser.Company</p>
        }
    </div>
</div>

integration-tests/samples/2.x/IntegrationTestsSample/src/RazorPagesProject/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Message System";
}

<h1>@ViewData["Title"]</h1>

<div class="row">
    <div class="col-md-8">

        <form id="addMessage" method="post">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">Add a message</h3>
                </div>
                <div class="panel-body">
                    <div class="form-group">
                        <label asp-for="Message.Text"></label>
                        <input asp-for="Message.Text" class="form-control">
                        <span asp-validation-for="Message.Text" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <button id="addMessageBtn" type="submit" asp-page-handler="AddMessage" class="btn btn-default">Add Message</button>
                    </div>
                </div>
            </div>
        </form>

    </div>
</div>

<div class="row">
    <div class="col-md-8">

        <form id="messages" method="post">
            <div class="panel panel-default">
                <div class="panel-heading clearfix">
                    <button id="deleteAllBtn" type="submit" asp-page-handler="DeleteAllMessages" class="pull-right btn btn-danger">Clear All</button>
                    <h3 class="panel-title" style="line-height:2.1">Messages</h3>
                </div>
                <div class="panel-body">
                    <ul>
                        @foreach (var message in Model.Messages)
                        {
                            <li>
                                <button id="deleteBtn@(message.Id)" type="submit" class="btn btn-danger" style="margin-bottom:2px" asp-page-handler="DeleteMessage" asp-route-id="@message.Id">Delete</button>
                                @message.Text
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </form>

    </div>
</div>

<div class="row">
    <div class="col-md-8">

        <form id="analyze" method="post">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">Analyze Messages</h3>
                </div>
                <div class="panel-body">
                    <div class="form-group">
                        <button id="analyzeBtn" type="submit" asp-page-handler="AnalyzeMessages" class="btn btn-default">Analyze</button>
                    </div>
                    <div class="form-group">
                        @Model.MessageAnalysisResult
                    </div>
                </div>
            </div>
        </form>

    </div>
</div>

integration-tests/samples/2.x/IntegrationTestsSample/src/RazorPagesProject/Pages/SecurePage.cshtml
@page
@model SecurePageModel
@{
    ViewData["Title"] = "Secure Page";
}

<h1>@ViewData["Title"]</h1>

<p>This is a secure page in the app.</p>

integration-tests/samples/2.x/IntegrationTestsSample/src/RazorPagesProject/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewData["Title"] - Razor Pages Testing Sample</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css">
        <link rel="stylesheet" href="~/css/site.css">
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u">
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true">
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-page="/Index" class="navbar-brand">Razor Pages Testing Sample</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-page="/Index">Home</a></li>
                    <li><a asp-page="/GithubProfile">Github Profile</a></li>
                    <li><a asp-page="/About">About</a></li>
                    <li><a asp-page="/Privacy">Privacy</a></li>
                    <li><a asp-page="/SecurePage">Secure Page (Requires Authentication)</a></li>
                    <li><a asp-page="/Contact">Contact</a></li>
                </ul>
                <partial name="_LoginPartial" />
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy;@System.DateTime.Now.Year - Razor Pages Testing Sample</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>